import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { WagmiProvider } from "@/components/wagmi-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <WagmiProvider>
      <html lang="en">
        <body className={inter.className}>
          <div vaul-drawer-wrapper="" className="bg-background">
            {children}
          </div>
        </body>
      </html>
    </WagmiProvider>
  );
}
